# Generated by Django 2.2.6 on 2019-11-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authorName',
            field=models.CharField(default='暂无', max_length=20, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='book',
            name='introduction',
            field=models.TextField(default='暂无', verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='book',
            name='pageNum',
            field=models.IntegerField(default=0, verbose_name='页数'),
        ),
        migrations.AddField(
            model_name='book',
            name='pressName',
            field=models.CharField(default='暂无', max_length=20, verbose_name='出版社'),
        ),
        migrations.AddField(
            model_name='book',
            name='pricingNum',
            field=models.IntegerField(default=0, verbose_name='定价'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookName',
            field=models.CharField(default='暂无', max_length=40, verbose_name='书籍名称'),
        ),
    ]
