# Generated by Django 2.2.6 on 2019-12-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191201_1601'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='ImageStore',
        ),
    ]
