# Generated by Django 2.2.6 on 2019-12-01 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Book'),
        ),
        migrations.AlterField(
            model_name='status',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Comment'),
        ),
        migrations.AlterField(
            model_name='status',
            name='read',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Read'),
        ),
    ]
