# Generated by Django 2.2.6 on 2019-12-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='user/user_normal.jpg', upload_to='user'),
        ),
    ]
